GLAD/NBR/COPING PGCED freeze 3
Helena-D/PGCED_Freeze3_KCL_pheno pull request #3
Opened 2022-02-22 13:56 UTC by Helena-D

2022-02-23 02:38 UTC, topherhuebel requested changes
@Helena-D
The script is looking good to me. Just a lot of tiny things. 
I recommend splitting the monster in several subscripts that we can run subsequently with a wrapper script.
If you split the script up, I’m happy to help with re-writing in tidyverse. We could do this script by script, because we need the variables also for EDGI analyses.
Please also use a credentials file for the file paths.
I’m having 1000 lines left, but I think if you could clean up the script and split it, it will make more sense than me saying the same thing over and over again

2022-02-23 02:38 UTC, topherhuebel commented on GLAD_NBR_PGCED3_cases.Rmd
> +dat_nbr_AN_screener <- readRDS(file = "/Users/helenadavies/King's College London/MT-TNG BioResource EDIT - ilovedata - ilovedata/data_raw/latest_freeze/coping_nbr/an_scr_coping_nbr.rds")
path

2022-02-23 02:38 UTC, topherhuebel commented on GLAD_NBR_PGCED3_cases.Rmd
> +dat_nbr_AN_screener %>%
dim and nrow is a duplicate

2022-02-23 02:38 UTC, topherhuebel commented on GLAD_NBR_PGCED3_cases.Rmd
> +dat_nbr_AN_screener %>%
dim and nrow duplicate

2022-02-23 02:38 UTC, topherhuebel commented on GLAD_NBR_PGCED3_cases.Rmd
> +
I don't understand why you don't define them as the inverse of your cases?
meaning not having AN, ANR, ANBP, BN, or BED or any other ED from the MHD?

2022-02-23 02:38 UTC, topherhuebel commented on GLAD_NBR_PGCED3_cases.Rmd
> +
The controls should be the same controls that we are using for all analysis?!

2022-02-23 02:38 UTC, topherhuebel commented on GLAD_NBR_PGCED3_cases.Rmd
> +1. Any individual who does not have a history of binge eating (narrow or broad definition) AND does not have a history of any eating disorder.
Binge eating, but then you say no_AN?
Why is no_AN not just
not AN, ANR, ANBP, BN, BED?

2022-02-23 02:38 UTC, topherhuebel commented on GLAD_NBR_PGCED3_cases.Rmd
> +# No atypical anorexia
They should just be your 0 of AAN when using the broadest definition of AAN?!

2022-02-23 02:38 UTC, topherhuebel commented on GLAD_NBR_PGCED3_cases.Rmd
> +# No history of other EDs (self-report)
Again, doesn't really make sense to define it like this or am I missing something?

2022-03-03 17:10 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +           mhd.bn_cop_numeric ==1 |
+ add to annotation (that ANB cases would be captured by lifetime bigne eating)

2022-03-03 17:15 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +               ANR_GLAD == 1 ~ "Both",
EDGI = no genotype data

2022-03-03 17:16 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +    • Has a self-reported diagnosis of anorexia nervosa binge-eating/purging (specification that this has been confirmed by a healthcare professional is not required for this definition)
ANB is covered by 'binge eating'. we have 5 GWASs: ANBP, ANR, AN, narrow BE, broad BE

2022-03-03 17:16 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +           mhd.bn_numeric == 1 |
covered by binge eating

2022-03-03 17:16 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +  a.	If ANBP or OSFED/EDNOS is diagnosed, these individuals will only be included if they explicitly state ‘subthreshold BN’ or ‘subthreshold BED’.
covered by binge eating

2022-03-03 17:17 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +            ed.DSM5_AN_restricting_bmi_20_binary_numeric == 1
to check!

2022-03-03 17:21 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +Work out weight at period of significant weight loss (COPING GLAD & NBR)
this is weight AFTER weight loss. aan.weight_prior_kg_total_cop is weight BEFORE

2022-03-03 17:21 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +dat_with_selfreport$aan.weight_lost_lbs <- dat_with_selfreport$aan.stone_pounds_lose_note_numeric
was already numeric

2022-03-03 17:22 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +# Remove age outliers
*bmi outliers!

2022-03-03 17:23 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +        (AAN_BMI <= 18.55 &
yes exactly - these are counted as AN cases. will rename 'AN_from_AAN_module'

2022-03-03 17:24 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +GLAD AAN Low BMI Count cases
yes - convoluted i know......

2022-03-03 17:25 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +All of the criteria for anorexia nervosa are met, except that despite significant weight loss, the individual’s weight is within or above the normal range (BMI of 20 or above)
need to change to AN definition

2022-03-03 17:25 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +         aan.1.gain_weight_afraid_fat_cop == "Extremely afraid") &
this is AN (no subtype) and we have not changed the BMI threshold

2022-03-03 17:29 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +
i have done them separately

2022-03-03 17:34 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +    an.bmi_lowest_cop > 18.55  # Lowest BMI as reported in ED100K optional questionnaire AN module, greater than 18.55
our definition of AAN is BMI above 18.5

2022-03-03 17:35 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +dat_nbr_health.id %>%
one is IBD, the other is IBS

2022-03-03 17:39 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +1. Any individual who does not have a history of binge eating (narrow or broad definition) AND does not have a history of any eating disorder.
There may be people who self-report BN/BED but do not endorse binge eating in the ED100K - will do a cross table to check this

2022-03-03 17:40 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +# No atypical anorexia
need to include the screener - people who say 'No' to screener need to be 0, the algorithm does not compute

2022-03-03 17:45 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +# No history of other EDs (self-report)
People who suspected but never been diagnosed with an eating disorder - ask about this agian!!!!!!

2022-03-04 11:30 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +              GLAD_BE_duration_months >= 3 &
the GLAD variables have "GLAD_" at the beginning whilst the GLAD COPING ones are left as they are, whilst the GLAD COPING have "COPING"

2022-03-04 11:31 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +          (
that is captured by binge eating

2022-03-04 11:32 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +           mhd.bn_cop_numeric ==1 |
done!

2022-03-04 11:43 UTC, Helena-D commented on GLAD_NBR_PGCED3_cases.Rmd
> +All of the criteria for anorexia nervosa are met, except that despite significant weight loss, the individual’s weight is within or above the normal range (BMI of 20 or above)
done (removed it)

2022-03-08 10:02 UTC, Helena-D commented
adding all files back (also hcnages to GLAD/NBR script following Topher's review)

2022-03-08 10:02 UTC, merged